name: Main

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Create packages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet pack --configuration Release --no-build --output ./packages
      - name: Publish packages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet nuget push ./packages/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate